version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "ci"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "python"

  - package-ecosystem: "docker"
    directory: "/challenges/examples/pwn/buffer_overflow/docker"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/challenges/examples/web/sql_injection/docker"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "docker"
