version: '3.8'

services:
  example-buffer-overflow:
    build: .
    ports:
      - "9999:9999"
    environment:
      - FLAG=is1abCTF{placeholder_flag}
      - TIMEOUT=60
    volumes:
      - ./logs:/home/ctf/logs
    restart: unless-stopped
    networks:
      - ctf-network
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp

networks:
  ctf-network:
    driver: bridge